/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionSlugRouteImport } from './routes/subscription.$slug'

const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionSlugRoute = SubscriptionSlugRouteImport.update({
  id: '/subscription/$slug',
  path: '/subscription/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/wheel': typeof WheelRoute
  '/subscription/$slug': typeof SubscriptionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/wheel': typeof WheelRoute
  '/subscription/$slug': typeof SubscriptionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/wheel': typeof WheelRoute
  '/subscription/$slug': typeof SubscriptionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/wheel'
    | '/subscription/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/wheel'
    | '/subscription/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/cart'
    | '/wheel'
    | '/subscription/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  WheelRoute: typeof WheelRoute
  SubscriptionSlugRoute: typeof SubscriptionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/$slug': {
      id: '/subscription/$slug'
      path: '/subscription/$slug'
      fullPath: '/subscription/$slug'
      preLoaderRoute: typeof SubscriptionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  WheelRoute: WheelRoute,
  SubscriptionSlugRoute: SubscriptionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
